# Generated by Django 3.2.7 on 2021-09-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210929_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Account.customuser')),
                ('company_name', models.CharField(max_length=50)),
                ('gst_no', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('bank_account', models.BigIntegerField()),
            ],
        ),
    ]
