# Generated by Django 3.2.7 on 2021-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
