# Generated by Django 3.2.8 on 2021-10-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
