# Generated by Django 3.2.7 on 2021-10-11 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0004_auto_20211002_1841'),
        ('Account', '0007_alter_customuser_managers'),
        ('CustomerProfile', '0003_alter_address_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.customer')),
                ('grocery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.grocery')),
                ('laptop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.laptop')),
                ('mobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerProfile.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.customer')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Customer.order_item')),
            ],
        ),
    ]
