# Generated by Django 3.2.7 on 2021-10-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_customuser_managers'),
        ('CustomerProfile', '0003_alter_address_address_type'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrders',
            new_name='Custorders',
        ),
    ]
