# Generated by Django 3.2.7 on 2021-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_rename_customerorders_custorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custorders',
            name='order_item',
        ),
        migrations.AddField(
            model_name='custorders',
            name='order_item',
            field=models.ManyToManyField(to='Customer.Order_item'),
        ),
    ]
