# Generated by Django 3.2.7 on 2021-10-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20211012_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custorders',
        ),
    ]
