# Generated by Django 3.2.8 on 2021-10-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0003_alter_address_address_type'),
        ('Seller', '0004_auto_20211002_1841'),
        ('Account', '0008_alter_customuser_managers'),
        ('Customer', '0004_delete_custorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile_no', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('items', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CustomerProfile.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.customer')),
                ('grocery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.grocery')),
                ('laptop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.laptop')),
                ('mobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.mobile')),
            ],
        ),
    ]
