# Generated by Django 3.2.7 on 2021-10-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('mobile', 'mobile'), ('laptop', 'laptop'), ('grocery', 'grocery')], max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=5)),
                ('rom', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('mimage', models.ImageField(upload_to='Mobiles/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=5)),
                ('rom', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('limage', models.ImageField(upload_to='Laptops/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=100)),
                ('gimage', models.ImageField(upload_to='Grocerys/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
            ],
        ),
    ]
