# Generated by Django 3.2.7 on 2021-10-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobile',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
