# Generated by Django 3.2.7 on 2021-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_auto_20211001_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='warranty',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='rom',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='warranty',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='rom',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='warranty',
            field=models.IntegerField(max_length=100),
        ),
    ]
