# Generated by Django 3.2.7 on 2021-10-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_customuser_managers'),
        ('CustomerProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(default=None, max_length=100)),
                ('mobile', models.BigIntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=500)),
                ('address_type', models.BooleanField(default=None)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerProfile.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerProfile.country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.customer')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerProfile.state')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
