# Generated by Django 3.2.7 on 2021-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0002_auto_20211005_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
